package cryptovalid

import (
	"bytes"
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"strings"
	"sync"
	"testing"
	"time"
)

// vectors.json is generated by vectors.py from the Python reference (stdlib json, ensure_ascii):
// input → canonical bytes → SHA-256. Go must reproduce every byte.
func TestCanonicalVectors(t *testing.T) {
	raw, err := os.ReadFile("vectors.json")
	if err != nil {
		t.Fatal(err)
	}
	var doc struct {
		Accept []struct{ Input, Canonical, Sha256 string }
		Refuse []struct{ Why, Text string }
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatal(err)
	}
	vs := doc.Accept
	if len(vs) < 11 || len(doc.Refuse) < 10 {
		t.Fatalf("only %d accept / %d refuse vectors", len(vs), len(doc.Refuse))
	}
	for _, r := range doc.Refuse {
		if _, err := Parse([]byte(r.Text)); err == nil {
			t.Errorf("accepted forbidden input (%s): %s", r.Why, r.Text)
		}
	}
	for _, v := range vs {
		val, err := Parse([]byte(v.Input))
		if err != nil {
			t.Fatalf("%s: %v", v.Input, err)
		}
		got, err := Canonical(val)
		if err != nil {
			t.Fatal(err)
		}
		if string(got) != v.Canonical {
			t.Errorf("canonical mismatch\n in:  %s\n got: %s\n want:%s", v.Input, got, v.Canonical)
		}
		s := sha256.Sum256(got)
		if hex.EncodeToString(s[:]) != v.Sha256 {
			t.Errorf("sha mismatch for %s", v.Input)
		}
	}
}

func TestRefusals(t *testing.T) {
	for _, bad := range []string{`{"x":1.5}`, `{"x":1e3}`, `{"x":1,"x":2}`, `{"x":9007199254740992}`, `{"x":-9007199254740992}`, "{\"x\":\"\xff\"}", `{"x":1} trailing`, `[1,2`} {
		if _, err := Parse([]byte(bad)); err == nil {
			t.Errorf("accepted forbidden input %q", bad)
		}
	}
}

func TestVerifyChain(t *testing.T) {
	good := `{"data":{"a":1},"idx":0,"prev_hash":"` + Genesis + `","ts":"2026-09-14T00:00:00Z","self_hash":"HASH0"}` + "\n"
	p0, _ := Payload(mustObj(t, strings.Replace(good, "HASH0", "x", 1)))
	h0, _ := Hash("sha256", p0)
	l0 := strings.Replace(good, "HASH0", h0, 1)
	e1 := `{"data":{"a":2},"idx":1,"prev_hash":"` + h0 + `","ts":"2026-09-14T00:00:01Z","self_hash":"HASH1"}` + "\n"
	p1, _ := Payload(mustObj(t, strings.Replace(e1, "HASH1", "x", 1)))
	h1, _ := Hash("sha256", p1)
	l1 := strings.Replace(e1, "HASH1", h1, 1)
	if v := VerifyLedger(strings.NewReader(l0 + l1)); v.Verdict != "PASS" {
		t.Fatalf("expected PASS, got %+v", v)
	}
	if v := VerifyLedger(strings.NewReader(strings.Replace(l0, `"a":1`, `"a":9`, 1) + l1)); v.Verdict != "FAIL" || v.HashRecomputePassed {
		t.Fatalf("tamper not detected: %+v", v)
	}
	if v := VerifyLedger(strings.NewReader(l1)); v.Verdict != "FAIL" || v.LinkPassed {
		t.Fatalf("head cut not detected: %+v", v)
	}
	if v := VerifyLedger(strings.NewReader("")); v.Verdict != "FAIL" {
		t.Fatalf("empty: %+v", v)
	}
	if v := VerifyLedger(strings.NewReader(l0)); v.Verdict != "PASS" {
		t.Fatalf("tail cut is INVISIBLE by design (declared): %+v", v) // documents the limit, does not hide it
	}
}

func TestAppendTailAndLock(t *testing.T) {
	p := t.TempDir() + "/l.jsonl"
	ts := time.Date(2026, 9, 14, 0, 0, 0, 0, time.UTC)
	var last string
	for i := 0; i < 50; i++ {
		h, err := Append(p, ts, map[string]any{"i": i, "s": strings.Repeat("x", 3000)}, "sha256")
		if err != nil {
			t.Fatal(err)
		}
		last = h
	}
	f, _ := os.Open(p)
	v := VerifyLedger(f)
	f.Close()
	if v.Verdict != "PASS" || v.Entries != 50 {
		t.Fatalf("%+v", v)
	}
	// tail reads only the last line even when it spans the 64 KiB chunk boundary (3 KB lines, 50 of them)
	rf, _ := os.Open(p)
	n, h, err := tail(rf)
	rf.Close()
	if err != nil || n != 50 || h != last {
		t.Fatalf("tail: %d %s %v", n, h, err)
	}
	// a corrupted last line stops the chain instead of continuing from a guessed state
	os.WriteFile(p, []byte("{\"idx\":0,\"self_hash\":\"zz\"}\n"), 0o600)
	if _, err := Append(p, ts, map[string]any{"a": 1}, "sha256"); err == nil {
		t.Fatal("append continued after an unreadable tail")
	}
	// float data refused, whole float accepted as integer (documented)
	if _, err := Append(t.TempDir()+"/f.jsonl", ts, map[string]any{"x": 1.5}, "sha256"); err == nil {
		t.Fatal("float accepted")
	}
	// 40 concurrent appenders across goroutines with their own file descriptors: flock keeps ONE chain
	q := t.TempDir() + "/c.jsonl"
	var wg sync.WaitGroup
	for g := 0; g < 40; g++ {
		wg.Add(1)
		go func(g int) {
			defer wg.Done()
			if _, err := Append(q, ts, map[string]any{"g": g}, "sha256"); err != nil {
				t.Error(err)
			}
		}(g)
	}
	wg.Wait()
	cf, _ := os.Open(q)
	cv := VerifyLedger(cf)
	cf.Close()
	if cv.Verdict != "PASS" || cv.Entries != 40 {
		t.Fatalf("concurrent appends forked the chain: %+v", cv)
	}
}

func TestMalformedEscapeAndGarbageFirstLine(t *testing.T) {
	if HasLoneSurrogate([]byte(`{"k":"\uzzzz"}`)) {
		t.Fatal("malformed escape labelled as lone surrogate")
	}
	if !HasLoneSurrogate([]byte(`{"k":"\ud800\uzzzz"}`)) {
		t.Fatal("high surrogate followed by garbage must be unpaired")
	}
	if _, err := Parse([]byte(`{"k":"\uzzzz"}`)); err == nil {
		t.Fatal("malformed escape accepted")
	}
	// garbage first line, then a valid genesis entry: FAIL (idx/garbage), profile still detected, no empty-algo hashing
	good := `{"data":{"a":1},"idx":0,"prev_hash":"` + Genesis + `","ts":"t","self_hash":"x"}`
	p, _ := Payload(mustObj(t, good))
	h, _ := Hash("sha256", p)
	v := VerifyLedger(strings.NewReader("{corrotto\n" + strings.Replace(good, `"x"`, `"`+h+`"`, 1) + "\n"))
	if v.Verdict != "FAIL" || v.Algo != "sha256" {
		t.Fatalf("garbage first line desynchronised the verifier: %+v", v)
	}
	if !strings.Contains(strings.Join(v.Failures, " "), "line 1") {
		t.Fatalf("garbage line not reported: %+v", v)
	}
}

func TestTornLastLine(t *testing.T) {
	p := t.TempDir() + "/t.jsonl"
	ts := time.Date(2026, 9, 14, 0, 0, 0, 0, time.UTC)
	if _, err := Append(p, ts, map[string]any{"a": 1}, "sha256"); err != nil {
		t.Fatal(err)
	}
	f, _ := os.OpenFile(p, os.O_APPEND|os.O_WRONLY, 0o600)
	f.WriteString(`{"idx":1,"ts":"t","prev_hash":"abc","data":{"b":`) // crash mid-write, no newline
	f.Close()
	_, err := Append(p, ts, map[string]any{"c": 3}, "sha256")
	if err == nil || !strings.Contains(err.Error(), "torn last line") {
		t.Fatalf("torn line not refused with a recovery hint: %v", err)
	}
}

func TestTornLastLineCompleteNoNewline(t *testing.T) {
	// council round 3 (Fable+Opus): a COMPLETE, parsable last line that lost only its '\n' (crash between the
	// last '}' and the newline, or a file truncated by one byte) must be refused too — otherwise Append writes
	// the next entry on the SAME line and the writer itself corrupts the chain ({...}{...}\n).
	p := t.TempDir() + "/t.jsonl"
	ts := time.Date(2026, 9, 14, 0, 0, 0, 0, time.UTC)
	if _, err := Append(p, ts, map[string]any{"a": 1}, "sha256"); err != nil {
		t.Fatal(err)
	}
	b, _ := os.ReadFile(p)
	if err := os.WriteFile(p, b[:len(b)-1], 0o600); err != nil { // drop the trailing newline only
		t.Fatal(err)
	}
	_, err := Append(p, ts, map[string]any{"c": 3}, "sha256")
	if err == nil || !strings.Contains(err.Error(), "torn last line") {
		t.Fatalf("complete line without newline not refused: %v", err)
	}
	b2, _ := os.ReadFile(p)
	if !bytes.Equal(b2, b[:len(b)-1]) {
		t.Fatalf("refused append still modified the file")
	}
	if v := VerifyLedger(bytes.NewReader(b2)); v.Verdict != "PASS" {
		t.Fatalf("a complete line without newline must still verify (positive control): %+v", v)
	}
}

func TestEmptyLedgerIsFail(t *testing.T) {
	// same rule as Python/JS (2026-09-11): zero entries = nothing verified = FAIL, never a third verdict
	for _, in := range []string{"", "\n\n", "   \n"} {
		v := VerifyLedger(strings.NewReader(in))
		if v.Verdict != "FAIL" || v.Entries != 0 || !strings.Contains(strings.Join(v.Failures, " "), "empty_ledger") {
			t.Fatalf("empty ledger %q not FAIL/empty_ledger: %+v", in, v)
		}
	}
}

func TestTrailingWhitespaceAfterNewlineIsNamedCorrectly(t *testing.T) {
	// council round 4 (Fable): `{...}\n   ` (an editor's trailing spaces) used to be reported as "no trailing
	// newline" although the newline IS there — safe, but the diagnosis lied and its recovery hint was wrong.
	p := t.TempDir() + "/t.jsonl"
	ts := time.Date(2026, 9, 14, 0, 0, 0, 0, time.UTC)
	if _, err := Append(p, ts, map[string]any{"a": 1}, "sha256"); err != nil {
		t.Fatal(err)
	}
	f, _ := os.OpenFile(p, os.O_APPEND|os.O_WRONLY, 0o600)
	f.WriteString("   ")
	f.Close()
	_, err := Append(p, ts, map[string]any{"c": 3}, "sha256")
	if err == nil || !strings.Contains(err.Error(), "trailing whitespace after the last newline") || strings.Contains(err.Error(), "torn") {
		t.Fatalf("whitespace tail not named correctly: %v", err)
	}
}

func TestVerifyStreamingDepthAndReporting(t *testing.T) {
	deep := strings.Repeat("[", 600) + strings.Repeat("]", 600)
	if v := VerifyLedger(strings.NewReader(`{"idx":0,"d":` + deep + `}` + "\n")); v.Verdict != "FAIL" || !strings.Contains(strings.Join(v.Failures, " "), "json_too_deep") {
		t.Fatalf("depth not refused: %+v", v)
	}
	// self_hash removed on entry 0 is reported ON entry 0 (not only as a link failure on entry 1)
	l0 := `{"data":{"a":1},"idx":0,"prev_hash":"` + Genesis + `","ts":"t"}` + "\n"
	v := VerifyLedger(strings.NewReader(l0))
	if v.Verdict != "FAIL" || !strings.Contains(strings.Join(v.Failures, " "), "entry 0: self_hash missing") {
		t.Fatalf("missing self_hash not reported on its own entry: %+v", v)
	}
}

func mustObj(t *testing.T, s string) *Object {
	v, err := Parse([]byte(strings.TrimSpace(s)))
	if err != nil {
		t.Fatal(err)
	}
	return v.(*Object)
}
